### ISSUE TITLE
With Copy Bundle ID enabled, 3D Touching automatically copies the ID.

### ISSUE THREAD

**Issue by burritosoftware** [tomaszpoliszuk/HomeScreenQuickActions#1]
Even if you don't hit the Copy ID button, 3D touching an icon copies it.

**Comment by tomaszpoliszuk** [comment]
Good catch - didn't thought to test it this way.

**Comment by tomaszpoliszuk** [comment]
Ok, seems like i've fixed it already in my internal build.
[[UIPasteboard generalPasteboard].string = bundleId;](https://github.com/tomaszpoliszuk/HomeScreenQuickActions/blob/master/HomeScreenQuickActions.xm#L153)
should be changed to [UIPasteboard generalPasteboard].string = item.localizedSubtitle; and moved to line 167.

I'll do some more tests tomorrow.

Thanks again for reporting this!

**Comment by tomaszpoliszuk** [comment]
This issue is now resolved and I've sent version 1.2.1 to BigBoss repo - it should be visible on repo as soon as 0ptimo will approve it :)

Thanks again [burritosoftware](https://github.com/burritosoftware)
