### ISSUE TITLE
Tweak doesn’t work after resprings

### ISSUE THREAD

**Issue by BLINK1337** [tomaszpoliszuk/HomeScreenQuickActions#2]
After doing a respring on my device the tweak no longer works. I have to go to settings and disable and enable it again to have it work. 

Edit: I meant the “show separators” option doesn’t work, not the entire tweak. The other options still work fine. It’s just that one. I’ve also noticed it seems to not work if the menu goes down from the icon but does still work on the icons where the menu goes upwards. I hope that makes sense, feel free to ask for any further info you need.

**Comment by tomaszpoliszuk** [comment]
That's awesome finding - I'll try to fix it as soon as possible, thank you!

**Comment by tomaszpoliszuk** [comment]
This bug as of version 1.5.1 is fixed - update is on BigBoss repo :)

Have a nice day!
